fixtures:
  repositories:
    archlinux_workstation:
      repo: "https://github.com/jantman/puppet-archlinux-workstation.git"
    archlinux_macbookretina:
      repo: "https://github.com/jantman/puppet-archlinux-macbookretina.git"
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.9.0"
    sudo:
      repo: "https://github.com/saz/puppet-sudo.git"
      ref: "v4.2.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.2.4"
    firewall:
      repo: "https://github.com/puppetlabs/puppetlabs-firewall.git"
      ref: "1.8.0"
    vcsrepo:
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
      ref: "1.3.1"
    staging:
      repo: "https://github.com/nanliu/puppet-staging.git"
      ref: "1.0.3"
    sysctl:
      repo: "https://github.com/duritong/puppet-sysctl.git"
      ref: "v0.0.11"
    inifile:
      repo: "https://github.com/puppetlabs/puppetlabs-inifile.git"
      ref: "1.4.2"
    ssh:
      repo: "https://github.com/saz/puppet-ssh.git"
      ref: "v2.8.1"
  symlinks:
    workstation_bootstrap: "#{source_dir}/puppet/modules/workstation_bootstrap"
