---
sudo: false
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"
rvm:
  - 2.3
env:
  - PUPPET_VERSION="~> 4.0"
notifications:
  email: false
