---
:backends:
  - yaml
:hierarchy:
  - defaults
  - "osfamily/%{::osfamily}"
  - "osfamily_productname/%{::osfamily}_%{::productname}"
  - user_config
:yaml:
  :datadir: /etc/puppetlabs/code/workstation-bootstrap/puppet/hiera
