---
:backends:
  - yaml
:hierarchy:
  - defaults
  - "os.family/%{::os.family}"
  - "os.family_productname/%{::os.family}_%{::productname}"
  - user_config
:yaml:
  :datadir: /etc/puppetlabs/code/workstation-bootstrap/puppet/hiera
