####################################################################
# github.com/jantman/workstation-bootstrap  -  User Configuration  #
#                                                                  #
# These variables must be updated for your specific configuration. #
####################################################################

# the username for your login user
username: jantman
# whether or not to purge all firewall rules at the global/firewall module level
firewall_purge: false
archlinux_workstation::makepkg_packager: Jason Antman <jason@jasonantman.com>
archlinux_workstation::ssh::extra_options:
  PubkeyAcceptedKeyTypes: +ssh-dss
archlinux_workstation::ssh::allow_users:
  - jantman
archlinux_workstation::user_groups:
  - sys
  - bumblebee
classes:
  - privatepuppet
remove_classes:
  - archlinux_workstation::all
